### ISSUE TITLE
chicken in green

### ISSUE THREAD

**Issue by Cyberpangolin** [MinetestForFun/server-minetestforfun#360] opened 2016-01-04 15:08 UTC
we probably need to check the white chicken texture... or it has some algae inside.
![capture du 2016-01-04 16 05 06](https://cloud.githubusercontent.com/assets/12512762/12092414/432e5fe2-b2fd-11e5-9ae8-4cce007553a3.png)

**Comment by Ombridride** [comment] 2016-01-04 15:28
No green lights for me, need more testimonies !
Maybe is it your graphical configuration ? Can you try with directx instead of openal for example ? with and without shaders ? with and without other important graphical parameters ?

**Comment by gravgun** [comment] 2016-01-04 15:51
This is due to the use of texture interpolation. For the same reason the borders of that torch are black, the pixels around the used areas on the chicken's texture happen to be green and "bleed" on the neighbouring pixels, causing this effect. Fixing would be easy: just add a same-coloured pixel margin around the texture.

**Comment by Ombridride** [comment] 2016-01-04 16:26
Ok, if it's the problem source, prefer a "black" background, the chicken has a black and a white texture, and in my point of view it's better if we see small black parts on the white texture

**Comment by Cyberpangolin** [comment] 2016-01-05 10:43
the glitch is directly linked with the normal-mapping. I de-activated it to avoid the issue

**Comment by LeMagnesium** [comment] 2016-01-17 15:26
> Fixing would be easy: just add a same-coloured pixel margin around the texture.

But then Minetest would consider this margin as a part of the texture, and use it for the edges of the texture, wouldn't it? And the margin's borders, pixels would bleed over them again?
I think, knowing this is a graphical glitch, that we don't have a proper solution for this...

**Comment by Ombridride** [comment] 2016-01-18 08:21
@LeMagnesium 
Anyway, we need to test it, if it doesn't work, It's a Minetest core related problem (again :p)...

**Comment by LeMagnesium** [comment] 2016-02-02 20:08
Tested and couldn't reproduce on my laptop.

**Comment by Ombridride** [comment] 2016-02-02 21:12
@LeMagnesium Can you give us your texture file ?
Someone else can test this file ?

**Comment by LeMagnesium** [comment] 2016-02-03 13:28
I meant that I just used the code and textures currently in the repository, with different graphical settings, and couldn't get any similar bug. I've seen bleeding colours already with bumbmapping but it doesn't happen with white chickens.

**Comment by Ombridride** [comment] 2016-02-03 18:47
And if, and if... the problem was the OPENGL version used by @Cyberpangolin on his client version ?

@Cyberpangolin you didn't answer me when i ask you the question about a test with DirectX option instead of OpenGL option in your client configuration, can you answer me please ?

**Comment by Ombridride** [comment] 2016-02-05 10:46
Up @Cyberpangolin ^

**Comment by fabienwang** [comment] 2016-02-08 17:55
Maybe @sct-0 would be interested in posting a picture of the chicken model she made :)

**Comment by sct-0** [comment] 2016-02-08 19:20
I made a chicken based on Simple Mobs (on which Mobs Redo is based) and the texture goes over the border. As far as I could see, what @LeMagnesium described does not happen, the border is just cut off.

@fabienwang You want it, you get it.
(Texture will be redone in several chicken-typical colours.)

![chicken](https://cloud.githubusercontent.com/assets/9308049/12896248/427e1dde-cea1-11e5-8d3b-11ca6a3e17ec.jpg)

**Comment by Ombridride** [comment] 2016-02-24 10:05
Thank you for your proposal @sct-0 but your model/texture is different from our model/texture, so this is not a good solution for us...

The green problem seems to be a graphic configuration problem and didn't seems to be a model/texture problem.

I closed this issue, but i will open an issue upstream to minetest engine, this green bug on this model still a strange thing... and it's clearly minetest engine related

**Closed** 2016-02-24 10:09 UTC
Labels: Media ➤ Graphics, Priority: Low
