### ISSUE TITLE
A giant sequoia popping on me :P

### ISSUE THREAD

**Issue by Cyberpangolin** [MinetestForFun/server-minetestforfun#356] opened 2016-01-03 20:57 UTC
I was in a old-generated zone (near the opera, in 222: -189) and a sequoia popped on me so I was inside it. kind of disturbing way of life :P

--> proposal: for all trees, or at least big ones check if a player is on it before it spawns.

**Comment by gravgun** [comment] 2016-01-03 22:01
I'll add to that proposal that the growth happens very quickly after. I.e. test every second if there's a player still there, else pop and stop the loop.

**Comment by Ombridride** [comment] 2016-01-03 22:25
Please, don't change the actual tree growth feature please, a globalstep isn't a good think, and if you want to be outside of the treetrunk you just have to move a little...

This "bug" is due to the trees growth "time offset" of the moretrees/plantlife mod which have a avoid lag purpose when the map is generating, and I think we don't need to make heavier the map generation with this kind of feature...

**Comment by gravgun** [comment] 2016-01-03 23:02
@Ombridride The implementation wouldn't be a globalstep! `<DIETY>` knows I hate that. Just a function called from the already-present three growth ABMs that will delay actual tree growth until there's no more players/entities on top of the sapling.

**Comment by farfadet46** [comment] 2016-01-04 10:01
the problem is there is no sapling where the sequoia spawn (maybe in some cave under the ground)

**Comment by Ombridride** [comment] 2016-01-04 15:26
@gravgun if you can do this without performence leaks (without global steps for example), do it ! :D

**Comment by Ombridride** [comment] 2016-02-05 10:47
@gravgun do you planned to work on this issue ?

**Comment by Ombridride** [comment] 2016-02-24 10:09
@ElementW do you planned to work on this issue ?

**Comment by ElementW** [comment] 2016-02-24 10:21
@Ombridride Nope, sorry. Not touching MT any more. (And anyway the odds of this pop issue happening are very slim)

**Comment by Ombridride** [comment] 2016-02-24 10:51
Ok, closed this issue, the tree pumping isn't really a problem because you aren't blocked, just move a little and you will see again the sky :)

**Closed by Ombridride** 2016-02-24 10:51 UTC
Labels: Modding ➤ BugFix, Priority: Low
