### ISSUE TITLE
we can cook all items in locked furnace but get nothing

### ISSUE THREAD

**Issue by farfadet46** [MinetestForFun/server-minetestforfun#478] opened 2016-06-22 15:46 UTC

**Comment by Cyberpangolin** [comment] 2016-06-22 22:05
Maybe that could give something related to lava, that could be crafted with a bucket to make a lava bucket?

**Comment by LeMagnesium** [comment] 2016-06-24 13:51
I can't cook stone, and I have no record of stone being cooked into another node.
What's the issue here?

**Comment by farfadet46** [comment] 2016-06-24 15:06
if i put a stone in a furnace, the stone is destroyed
PS i use my locked furnace (i don't know if this information is necessary)

**Comment by farfadet46** [comment] 2016-06-25 18:50
yes there is fuel, and i see an ultra-fast "arrow animation" (when the stone is burned) the stone are destroyed ultra-fast too

**Comment by LeMagnesium** [comment] 2016-06-25 18:54
Where is that furnace? Have you tried with a new one?

**Comment by farfadet46** [comment] 2016-06-25 19:20
the furnace is at my factory / home, if i put a cobble, it' use a coal and if i put a non burnable item when the flame is on, the item is burned .
if i put the same item without flame, it's not burned

**Comment by LeMagnesium** [comment] 2016-06-26 15:10
Can you try to destroy it and put it back?

**Comment by farfadet46** [comment] 2016-06-26 17:27
after replace the locked furnace, same problem, wen the furnace is active, it don't check if the item can be smelt or not, if not, the item is destroyed.

**Comment by Darcidride** [comment] 2016-08-12 15:30
Up, Is this issue fixed ?

**Comment by LeMagnesium** [comment] 2016-08-18 17:15
> Up, Is this issue fixed ?

I don't even understand fully what is the issue and whether or not there is one. Everything works fine for me on both the server and my local instance of it.

**Comment by Darcidride** [comment] 2016-08-18 19:21
Well, i close this issue, @farfadet46 will reopen this issue if the problem is still here.

**Comment by AcidNinjaFWHR** [comment] 2016-08-20 11:57
I just tested on the server and he's right.
Once my locked furnace was cooking some corn and it finished, I just put some random stuff, a wool in it while the fire was still active, and it just disappeared ! ;)

**Comment by crabman77** [comment] 2016-08-20 16:31
Fixed https://github.com/MinetestForFun/server-minetestforfun/commit/6d5a0d10560bb8d89667912e7dd7a5288a4c55d4

**Closed by crabman77** 2016-08-20 16:31 UTC
Labels: Modding ➤ BugFix, Priority: Medium, Unknown Source

**Comment by Darcidride** [comment] 2016-08-20 17:05
@crabman77 
Thank you for your work
This fix need to be pushed on all of our servers (except HG)
