### ISSUE TITLE
Default trees grow slower than moretrees' ones

### ISSUE THREAD

**Issue by Cyberpangolin** [MinetestForFun/server-minetestforfun#373] opened 2016-01-07 20:46 UTC
Strange thing:

plant a default:sapling in a cave
It won't grow

plant a moretrees tree (a beech by example)
It grows

as all farmed food can grow in caves, I suppose all trees coming from the mode default should be able to grow in caves too. Of course this should only happen with enough light.

**Comment by fabienwang** [comment] 2016-01-07 20:49
+1.Happened to me at -1365.

**Comment by Ombridride** [comment] 2016-01-07 20:53
Reported a long time ago to VanessaE, she said it was possible because she haven't any way to forbidden it with LUA...
Let's see if on of our great developers have an idea :p

**Comment by LeMagnesium** [comment] 2016-01-07 21:39
Do you want us to debug default's trees so that they can grow in caves too? Ok. Why not. But...
Look at those lines :
```
	local name_under = node_under.name
	local is_soil = minetest.get_item_group(name_under, "soil")
	if is_soil == 0 then
		return false
	end
```
(from [here](https://github.com/MinetestForFun/server-minetestforfun/blob/master/minetestforfun_game/mods/default/trees.lua#L14))

```
	local ll = minetest.get_node_light(pos)
	if not ll or ll < 13 then -- Minimum light level for growth
		return false          -- matches grass, wheat and cotton
	end
```
(from [here](https://github.com/MinetestForFun/server-minetestforfun/blob/master/minetestforfun_game/mods/default/trees.lua#L19))

Those are perfectly normal conditions to be met in order to grow a tree : soil, and sunlight. I understand the need to grow trees even underground, where there is not enough light to, but I don't think modifying all trees is a good idea. Yet, I think of something : what about bonemeals? They use a separate `can_grow` function, so we can ignore the low sunlight level and only focus on growing over soil nodes. We wouldn't add bonemeals like in Creative, where they are in free-access and can grow much more trees than the original version could. We could add `bonemeal` with a complicated craft recipe so that it would cost and people would not want to use them when they can just wait a bit, but rather underground where there is not enough sunlight to convert a sapling into a tree. Or otherwise we could restrict its use to below a certain altitude.
This is the clean way of proceeding. The other would be to remove those snippets above and make growing trees completly inconsistent to the rules of biology.

**Comment by Ombridride** [comment] 2016-01-07 22:44
The fact is all trees shouldn't grow in caves, that's the point of the issue
Maybe the solution is just an addition of a "y" level condition for the tree growth ? (moretrees only)

**Comment by Cyberpangolin** [comment] 2016-01-08 00:19
+1 to forbid any tree to grow in caves naturally, BUT with enough space AND light AND bone meal I would love to have a way to make them grow where I want, even in caves.

Basically, IRL, a tree doesn't care about where it is and will grow as much as it can with light and the good amount of fertilizer, so I think that the bone meal is a good solution if we can combine it with a minimum amount of light (say 12= a superglowglass on the next block). 

Maybe the bones could come from cats? 
A good way of recycling and another good reason to kill them ;)
Another way to explore: bones could be a loot from the oerkkis or rats, which are in caves too.

I suggest the following craft: bones -> bone powder
8 mese shards around 1 bone powder -> 2 bone meal
1 bone meal = 25% of efficiency
-> you basically need ~1.8 mese and to kill at least 2 mobs to have 1 tree. That tree can be essential to continue your trip in caves, so I'm sure I would pay that "tribute"

If it's totally forbidden to any tree to spawn in caves, then we probably have to reconsider the right to grow anything (I mean: food), but it would become impossible to stay a long time in caves. It's a bad thing, according that some player go really deep (-2000) and their surface home is far away from the /spawn point.

Please note: I know there was some bone meal before, that was never used. I wanted to but could not because I could not find any way to have some...

**Comment by farfadet46** [comment] 2016-01-08 12:25
or like in minecraft make some dongeon or mineshaft where we can fint bonemeal.

anywhere i think i's a good idea to make a long craft.

like need some gravel sand, clay, dirt to make a special node
where we need to add some cotton seed or wheat seed we get a more special node
... one addition
...one addition
... add some bone (given rarely by monster)
and get our precious.

this precisous like @Cyberpangolin says, nee a % efficiency.

in this case we can add this item and make this item too complex to not use when we can simply wait for it grow.

PS: sorry for my english :/

**Comment by Ombridride** [comment] 2016-01-08 13:12
In my point of view, a rare item like "bonemeal", if we add it, need to be a dropped only by a boss, maybe the Ent boss ? :)

**Comment by LeMagnesium** [comment] 2016-01-08 17:19
I personally think the current situation is good : can_grow checks for the light level, which is supposed to be low in caves unless we use powerful light nodes (like super glowing glasses), which is the same in real life. Why would be prevent trees from growing underground in caves if they have all required condition by real life trees (okay, the most important ones, except humidity/water) to grow?

**Comment by ObaniGemini** [comment] 2016-01-08 17:23
I don't think bonemeals should be a drop, as bonemeal is a single use item.

**Comment by farfadet46** [comment] 2016-01-08 19:45
okay @LeMagnesium point one think cool maybe add a difficult craft item special for lighting caves ?

**Comment by LeMagnesium** [comment] 2016-01-09 11:27
@farfadet46 : You already have items able to produce enough light, and you can't restrict their uses : torches, (super) glowing glasses. You can't restrict their use, that would be ridiculous. The point I developed earlier was that there is simply no good way of solving this issue since there is no issue. Trees grow underground if they have enough light and soil and that's it, you can't do anything about this (unless it's very stupid).

**Comment by Ombridride** [comment] 2016-01-09 15:54
The problem with the trees in caves are when sapling are putted into lava, the fire is disabled, so the tree will grow on lava, that's a little ridiculous.
An another point to think about is the grow-timer of a moretrees sapling, if you put a torch near a sapling, the sapling will grow instantly due to its grow-timer

**Comment by ObaniGemini** [comment] 2016-01-09 20:38
@Ombridride : bringing lava to the surface would end in the same ;)

**Comment by Ombridride** [comment] 2016-01-09 21:53
@ObaniGemini 
No, because the lava in surface are in volcano which are coded to don't have dirt nodes into them, so no sapling into lava on surface

**Comment by ObaniGemini** [comment] 2016-01-10 08:35
was lava bucket removed ?

**Comment by LeMagnesium** [comment] 2016-01-10 12:53
> if you put a torch near a sapling, the sapling will grow instantly due to its grow-timer

How are lighting and the grow-timer related?
We should clarify what has to be fixed in this issue. Is it about an imbalance problem? Or something else?

**Comment by fabienwang** [comment] 2016-01-10 21:54
Hello, here is a feedback on the original problem.
I was surprised that a default tree wouldn't grow in my cave house, while a tree from more_trees would grow everytime.
The problem is not related to the light or the height but it seems to be related to the "chance" parameter which is defined in minetest_game/default/trees/ mod.
It is in contradiction with more_trees mod where there is no chance parameter which means those trees grow everytime.

I think we should either set the same chance or remove the chance parameter so that every tree grow the same way.

**Comment by LeMagnesium** [comment] 2016-01-16 17:24
So it's not at all related to caves. I see.
So we need to either balance trees, or just make standard trees spawn faster.

**Comment by Ombridride** [comment] 2016-01-18 08:23
Make standard trees spawn faster seems good to me

**Comment by LeMagnesium** [comment] 2016-02-02 20:06
There, they grow "a little bit" faster : https://github.com/MinetestForFun/server-minetestforfun/commit/9d5b804399f064f65c630cf7938e354bd73b079e

**Comment by Ombridride** [comment] 2016-02-02 21:07
Perfect, good job @LeMagnesium 

I closed the issue.

**Closed by Ombridride** 2016-02-02 21:07 UTC
Labels: Modding ➤ BugFix, Priority: Low
